tailscale/sqlite

cgosqlite/cgosqlite.go, cgosqlite/cgosqlite.h, sqlite_test.go
Avoids `free(): double free detected in tcache 2`
Signed-off-by: David Crawshaw <crawshaw@tailscale.com>
=> sqlite: fix empty string handling

cgosqlite/cgosqlite.go, cgosqlite/cgosqlite.h, sqlite.go, sqlite_test.go, sqliteh/sqliteh.go
Best read commit-by-commit. Each includes relative benchmark performance to the commit before. Overall results of this PR:
```
name        old time/op  new time/op  delta
Persist-24  2.68µs ± 1%  2.03µs ± 1%  -24.00%  (p=0.000 n=20+20)
```
=> sqlite: speed up persistent queries

cgosqlite/cgosqlite.h, sqlite.go, sqliteh/sqliteh.go
Grinding away at cgo overhead.
name          old time/op  new time/op  delta
EmptyExec-24   439ns ± 0%   386ns ± 0%  -12.00%  (p=0.000 n=19+17)
Signed-off-by: David Crawshaw <crawshaw@tailscale.com>
=> sqlite, etc: move reset into step_result

cgosqlite/cgosqlite.go, cgosqlite/cgosqlite.h, sqlite.go, sqlite_test.go, sqliteh/sqliteh.go
Our expected use of this will be as an "event" API, not a tracing API.
But for future users, I included a traceID, that could be used to
retrofit one of those large trace/span systems onto the driver if you
were so inclined.
Minimal benchmark impact:
Persist-24    1.93µs ± 1%  1.92µs ± 1%  -0.51%  (p=0.000 n=19+18)
EmptyExec-24   386ns ± 0%   401ns ± 1%  +3.85%  (p=0.000 n=17+20)
Signed-off-by: David Crawshaw <crawshaw@tailscale.com>
=> sqlite, etc: add tracing API

sqlite.go
sqlite3_close doesn't close the DB unless all the prepared statements
are finalized. Callers of the package can get this right for
non-persistent queries, but for the persistent ones we need to clear our
internal cache.
This doesn't have a test because the sql.Conn.Close method eats errors
from the driver. Easily manually testable by taking SQL-based tests and
running them with -count=1000, as you run out of fds.
Signed-off-by: David Crawshaw <crawshaw@tailscale.com>
=> sqlite: really close

AUTHORS, CODE_OF_CONDUCT.md, LICENSE, PATENTS, SECURITY.md
pkg.go.dev won't show me the documentation for this package because it can't figure out the license. While I was at it, figured I'd add github-friendly metafiles like security and code of conduct as well.
=> Add license, author and other metadata files.

sqlite.go, sqlite_test.go
Don't call BEGIN until a transaction actually gets used, so that if a caller calls BeginTx then Rollback, there's no cgo+db accounting.
```
name            old time/op  new time/op  delta
BeginTxNoop-10  1.84µs ± 0%  1.10µs ± 1%  -39.93%  (p=0.000 n=9+10)
```
=> sqlite: delay BEGIN on transactions

cgosqlite/cgosqlite.go, cgosqlite/cgosqlite.h, sqlite_test.go
--- FAIL: TestTrace (0.00s)
sqlite_test.go:522: trace: improbable duration: -513288h42m26.15796988s
sqlite_test.go:523: trace: improbable duration: -513288h42m26.15796988s
sqlite_test.go:558: trace: improbable duration: 0s
Two problems:
1. It turns out CLOCK_MONOTONIC is 6 on macOS. Oops.
My comment claims it was defined as 1 in the POSIX spec,
but now I can't find it. So I can only say it's 1 on linux.
2. clock_gettime does not seem to have much resolution on
macOS, so I see some zeros. Ignore them.
=> sqlite, cgosqlite: fix TestTrace on macOS

sqlite.go, sqlite_test.go
This avoids deadlocks caused by ATTACHed database lock ordering.
Test adapted from one @dsnet wrote.
=> sqlite: use BEGIN IMMEDIATE by default

cgosqlite/cgosqlite.go
Fixes this error when cross-compiling for Android:
```
/usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Signed-off-by: Ilya Mateyko <me@astrophena.name>
=> cgosqlite: don't link against librt on Android

sqlite.go, sqlite_test.go, sqliteh/sqliteh.go, sqlstats/sqlstats.go
So we can use the Tracer without the driver.
=> sqlite, sqliteh: move Tracer interface

go.mod, sqlite.go, sqlite_test.go, sqliteh/sqliteh.go, sqlstats/sqlstats.go
This uses the sqlstats tracer to track current active transactions, and
how long they have been running for.
The database/sql driver does not have a Tx reason to plumb into 'why',
but the new sqlitepool does.
=> sqlstats, sqliteh: connection stats, and plumb why

sqlitepool/queryglue.go, sqlitepool/queryglue_test.go, sqlitepool/sqlitepool.go, sqlitepool/sqlitepool_test.go, sqlitepool/util.go
This is intended as a replacement for our internal sqlitedb package
pool and its TxWrapper.
It needs a little more machinery to be dropped in that's not covered in
this PR, in particular:
- helper functions that mimic ExecContext/QueryContext/QueryRowContext
to make replacing the existing uses of TxWrappers easy
- a little more Tracer plumbing, so we can get SQL query exec times
out in the same format we are used to them now
- a few other missing counters
This PR implements the Tx/Rx object split we've discussed a few times.
It will take a bit of work to make good use of that internally. But I
figured it's worth getting in now.
After we've replaced the current pool, I plan to have the code generator for queries work directly on top of this pool.
Any other features you want to see in a …
=> sqlitepool: new package, implements a pool

cgosqlite/cgosqlite.go, cgosqlite/cgosqlite.h, sqlite_test.go
```
│    before    │                after                 │
│    sec/op    │    sec/op     vs base                │
WALHookAndExec-8           2.354µ ±  7%   2.465µ ± 28%        ~ (p=0.812 n=10)
Persist-8                  2.054µ ±  1%   2.026µ ±  3%   -1.36% (p=0.043 n=10)
QueryRows100MixedTypes-8   42.79µ ±  1%   37.75µ ±  1%  -11.78% (p=0.000 n=10)
EmptyExec-8                378.2n ±  0%   355.2n ±  1%   -6.09% (p=0.000 n=10)
BeginTxNoop-8              9.445µ ± 38%   9.258µ ±  2%   -1.98% (p=0.002 n=10)
geomean                    3.747µ         3.618µ         -3.45%
│    before    │                after                 │
│     B/op     │     B/op      vs base                │
WALHookAndExec-8             56.00 ± 0%     48.00 ± 0%  -14.29% (p=0.000 n=10)
Persist-8 …
```
=> cgosqlite: remove some cgo allocs

cgosqlite/cgosqlite.go, cgosqlite/cgosqlite.h, sqlite.go
The https://pkg.go.dev/database/sql/driver#Value type can be either string or []byte, but []byte permits database/sql scanning into *sql.RawBytes without allocating. We were previously returning strings all the time if that's what SQLite thought it was. (But Go doesn't distinguish between "TEXT" and "BLOB" ... either are just some bytes)
This effectively moves any allocation (from []byte to string or []byte to clone of []byte) later, letting it be managed by database/sql.
│   before    │               after                │
│   sec/op    │   sec/op     vs base               │
QueryRows100MixedTypes-8   37.61µ ± 1%   36.60µ ± 0%  -2.67% (p=0.000 n=10)
│    before    │                after                 │
│     B/op     │     B/op      vs base                │
QueryRows100MixedTypes-8 …
=> sqlite: support sql.RawBytes (return []byte in driver.Value)

cgosqlite/cgosqlite.go, cgosqlite/cgosqlite.h
=> cgosqlite: remove allocs in bind_{int64,null,double}

cgosqlite/cgosqlite.go, cgosqlite/cgosqlite.h, sqlite.go, sqliteh/sqliteh.go, sqlitepool/queryglue.go, sqlitepool/sqlitepool.go, sqlitepool/sqlitepool_test.go
This recovers the performance loss from the prior commit's bug
fix (#66). Compared to before that, we're now even slightly faster at:
```
│   before    │               after2               │
│   sec/op    │   sec/op     vs base               │
WALHookAndExec-8           2.316µ ± 2%   2.297µ ± 1%       ~ (p=0.109 n=10)
Persist-8                  1.980µ ± 1%   1.956µ ± 0%  -1.26% (p=0.000 n=10)
QueryRows100MixedTypes-8   36.44µ ± 2%   36.47µ ± 1%       ~ (p=0.289 n=10)
EmptyExec-8                357.0n ± 2%   355.1n ± 1%       ~ (p=0.697 n=10)
BeginTxNoop-8              9.178µ ± 0%   9.178µ ± 2%       ~ (p=0.684 n=10)
geomean                    3.529µ        3.512µ       -0.50%
│    before    │                after2                 │
│     B/op     │     B/op      vs base                 │ …
```
=> cgosqlite: get column types during Step

cgosqlite/cgosqlite.go, cgosqlite/cgosqlite.h, cgosqlite/walcallback.go
As per the last comment of golang/go#48824, `_GoStringLen` and `_GoStringPtr` are declared in the preamble unless `//export` is used. To fix the problem, the exported WAL callback function needs to be moved to a separate file.
This removes compiler errors under certain conditions. The most easy way to reproduce this is by attempting to use `dlv`. For some reason, a normal `go` build still succeeds but a `dlv` build does not.
Fixes #75
=> cgosqlite: move WAL callback to its own file

sqlitepool/queryglue.go
Turns out the described conditions only hold for binding on standard SQL tables. If you use something like FTS5, you can get SQLITE_MISUSE on bind based on user-provided strings. E.g. if you try to search text for something like "autogroup:shared" it turns out FTS5 parses the ':' on bind and treats the prefix as an SQL table column name and returns a MISUSE error, which you don't want to turn into a panic.
So do the boring thing and return an error.
Updates #cleanup
=> sqlitepool: remove overly clever panic on bind error

cgosqlite/cgosqlite.go, sqlite.go, sqlite_test.go, sqliteh/sqliteh.go
By default, a query with a time-consuming step may ignore termination of the
context passed in by the driver. Add an option allowing the caller to stipulate
that such queries should be explicitly interrupted (vi sqlite3_interrupt) when
the context ends. This option is disabled by default.
=> sqlite: add an optional explicit interrupt on context termination

sqlite.go
In #85 we added an optional mechanism to forcibly interrupt a query that
exceeds its context's lifespan. Move the cancellation during query close until
after cleanup, so that the cancellation of a successful query does not race
with cleanup for setting the result code. (It is not a data race, the accesses
are properly synchronized, but we don't want the cancellation to win unless the
query is actually still running).
=> sqlite: cancel completed queries after cleanup, not before

cgosqlite/cgosqlite.go, sqlite_test.go
Presenting a query consisting of only comments results in a statement with a
NULL underlying cStmt. The SQL text is syntactically valid, but when attempting
to clean up after a query on such a statement, the indirection through NULL
triggers a panic.
Check during cleanup for this degenerate case, and don't try to reset the
statement in that case. Add a regression test for the original failure.
Signed-off-by: M. J. Fromberger <fromberger@tailscale.com>
=> cgosqlite: do not attempt to reset a NULL statement

sqlstats/sqlstats.go, sqlstats/sqlstats_test.go
This PR exports the QueryStats and Collect method so it can be used to gather statistics and used during tests.
Used in https://github.com/tailscale/corp/pull/16678
=> sqlstats: export Collect for metrics in tests

sqlstats/sqlstats.go, sqlstats/sqlstats_test.go
I failed to test the previous Reset implementation with `-race`, thinking that because it was only used in a Test, a straightforward zeroing of all of the fields would suffice. This proved not to be the case, and so I'm fixing it now:
```
$ go test ./sqlstats/ -run Race -race -count 20
ok  	github.com/tailscale/sqlite/sqlstats	21.289s
```
=> sqlstats: fix Tracer.Reset data races

sqlite.go, sqlite_test.go
Probably a typo. Fixes errors like this:
```
cannot parse time from column 3: parsing time "2024-03-08 18:41:53" as "2006-01-02 15:04:05.000-0700": cannot parse "" as ".000"
```
Signed-off-by: Ilya Mateyko <me@astrophena.name>
=> sqlite: fix short time parsing

cgosqlite/cgosqlite.h
This has been missing for some time, but my compiler driver got stricter and started failing on this.
=> cgosqlite: include time.h for clock_gettime

cgosqlite/cgosqlite.go, cgosqlite/cgosqlite.h
Unless this is defined a strict compiler will error with an implicit definition error at least, or at worst will not even find a definition as one may optionally not be provided at all:
```
./cgosqlite.h: In function 'monotonic_clock_gettime':
./cgosqlite.h:52:9: error: implicit declaration of function 'clock_gettime' [-Wimplicit-function-declaration]
52 |         clock_gettime(CLOCK_MONOTONIC, t);
|         ^~~~~~~~~~~~~
```
As a very minor change: use the system import syntax for system imports.
=> cgosqlite: use POSIX 2014 explicitly

.github/workflows/test-sqlite.yml, cgosqlite/cgosqlite.go
This fixes the regression, also adds a macOS CI pipeline.
=> Fix macOS build regression from XOPEN_SOURCE=600

cgosqlite/shell.c.disabled, cgosqlite/sqlite3.h, cgosqlite/sqlite3ext.h
The 3.45 series has been out long enough now that the initial JSONB issues have shaken out, and fixes to some regressions in the 3.44 series.
Of some interest are:
- Fix a couple of obscure UAF errors and an obscure memory leak.
- In partial index scans, if the WHERE clause implies a constant value for a table column, replace occurrences of that table column with the constant. This increases the likelihood of the partial index being a covering index.
- JSONB types.
=> cgosqlite: update to SQLite 3.45.3

sqlstats/sqlstats.go
And split the QueryStats type into an internal accounting half (with
the atomics) and a public half (with natural types).
Updates tailscale/tailscale#5210
=> sqlstats: use Go 1.19 atomics, round MeanDuration more

cgosqlite/cgosqlite.go
SQLITE_TEMP_STORE=1 allows PRAGMA temp_store = MEMORY, while keeping temporary files as the default behavior for temporary storage.
This can be used to accelerate some migrations, when building an in-memory temporary btree to use in a later correlated subquery is faster than the query planner would normally do things, for example when optimizing locality or btree operation order.
=> cgosqlite: set SQLITE_TEMP_STORE=1

cgosqlite/cgosqlite.go, cgosqlite/cgosqlite.h
Just removes duplicate imports and orders them better.
=> cgosqlite: cleanup the import layout some more

go.mod, sqlite.go, sqlite_test.go
(A restatement of #87)
The optional cancellation hook in #85 and #86 has a deficiency: If the query successfully completes before its context ends, the cleanup context would unconditionally trigger an interrupt on the database connection. That interrupt could race with a subsequent query on that connection, and cause a spurious cancellation.
To fix this, separate the cleanup context from the input context, and only effect an interrupt if the _input_ context terminates before cleanup occurs. Only if cleanup is definitively prior to the query finishing will we effect an explicit interrupt.
Also: Add a test that demonstrates the original problem.
=> sqlite: fix handling of "early" context cancellations

sqlite.go, sqlite_test.go
I did not test the changes in #103 sufficiently, and missed a corner case in
ExecContext: We need to make sure the context cleanup happens prior to the
synchronization, not in a defer.
Add a test to actually trigger this case, and fix the cleanup so it happens
before return as intended.
=> sqlite: fix cancellation cleanup for ExecContext

cgosqlite/cgosqlite.go
This is a relatively recent issue, so should likely be fixed upstream in either sqlite or gcc. But in the meantime, quiet this warning.
Updates #cleanup
=> cgosqlite: quiet bogus gcc warning

cgosqlite/cgosqlite.go
Some Clang builds, notably the one shipped on ARM by Apple, do not understand
all the same warning flags that GCC does. Suppress spurious warnings for these
to avert build noise.
Updates tailscale/corp#21834
=> cgosqlite: silence warnings about unknown warnings

README.md, cgosqlite/cgosqlite.go, cgosqlite/shell.c.disabled, cgosqlite/sqlite3.h, update-sqlite.sh
- Add script to partially automate SQLite updates
- Run with https://sqlite.org/2024/sqlite-amalgamation-3460100.zip
- Removed compiler warning suppression that is no longer required.
Updates https://github.com/tailscale/corp/issues/22321
=> cgosqlite: import SQLite amalgamation v3.46.1
